### ISSUE TITLE
Optional round argument?

### ISSUE THREAD

**Issue by kkimdev** [eCollect/node-fe1-fpe#3]
Hi, I noticed that the round is hard-coded, how about providing an optional round argument?

fwiw, botan also has round as an argument https://botan.randombit.net/manual/fpe.html

**Comment by nanov** [comment]
Hi and sorry for the delay,

This definitely could be implemented ( a PR is welcome ), would do it in a completely separated class ( as botan does ) in order to keep the interfaces in tact.

**Comment by sp1tz** [comment]
The link provided resolves to https://botan.randombit.net/handbook/
As such, I was not able to find the reference implementation.

[PR is out.](https://github.com/eCollect/node-fe1-fpe/pull/4)
